export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const REGISTER_BEGIN = "REGISTER_BEGIN";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const LOGOUT = "LOGOUT";
export const SET_ROLE = "SET_ROLE";

export const PRODUCT_LIST = "PRODUCT_LIST";
export const REGISTER_PRODUCTS = "REGISTER_PRODUCTS";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const DELL_PRODUCTS = "DELL_PRODUCTS";

export const RUNLINE_LIST = "RUNLINE_LIST";
export const REGISTER_RUNLINE = "REGISTER_RUNLINE";
export const DELL_RUNLINE = "DELL_RUNLINE";
export const UPDATE_RUNLINE = "UPDATE_RUNLINE";

export const USERS = "USERS";

export const REGISTER_SHOW = "REGISTER_SHOW";
// export const REGISTER_BEGIN_SHOW = "REGISTER_BEGIN_SHOW";
// export const REGISTER_FAILED_SHOW = "REGISTER_FAILED_SHOW";
export const LIST_SHOW = "LIST_SHOW";
export const UPDATE_SHOW = "UPDATE_SHOW";
export const DELL_ITEM_SHOW = "DELL_ITEM_SHOW";
export const LIST_CAC = "LIST_CAC";
export const LIST_CACIB = "LIST_CACIB";

export const CART_ADD_PRODUCT = "CART_ADD_PRODUCT";
export const CART_CLEAR = "CART_CLEAR";
export const CART_LOAD_PRODUCT = "CART_LOAD_PRODUCT";
export const CART_PLUS_PRODUCT = "CART_PLUS_PRODUCT";
export const CART_MINUS_PRODUCT = "CART_MINUS_PRODUCT";
//export const CART_DEL_ITEM_PRODUCT = "CART_DEL_ITEM_PRODUCT";

export const CHECKOUT = "CHECKOUT";
export const ORDERS = "ORDERS";
export const CHACK_STATUS = "CHACK_STATUS";
export const ORDERITEMS = "ORDERITEMS";
